#!/bin/bash

set -e


is-update-available () {
    [[ -f latest ]] && {
        LATEST_INSTALLED=$(cat latest)
        rm latest
    }

    wget https://github.com/valcalen/cosymo-mirror/raw/master/latest
    LATEST_AVAILABLE=$(cat 'latest')

    [[ "$LATEST_INSTALLED" = "$LATEST_AVAILABLE" ]] && return 1
    return 0
}

update () {
    # remove files that will be updated
    [[ -f cosymo.jar ]] && rm cosymo.jar
	[[ -f cosymo ]] && rm cosymo
	
	
	# fetch application starter
    wget https://github.com/valcalen/cosymo-mirror/raw/master/cosymo
    chmod +x cosymo

	# fetch program files
    wget https://github.com/valcalen/cosymo-mirror/raw/master/cosymo.zip
    unzip -u cosymo.zip
    rm cosymo.zip
    
    # execute post-install script (if present)
    [[ -x postinstall ]] && {
    	. postinstall
    	rm postinstall
    }
}


run () {
    java -jar cosymo.jar $*
}


if is-update-available; then
    update
fi

run
